apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: project
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: project
  template:
    metadata:
      labels:
        app: techtrends
        tag: project
    spec:
      containers:
      - image: abdlquadri/techtrends
        imagePullPolicy: IfNotPresent
        livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3111
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
        name: techtrends
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        ports:
            - containerPort: 3111
              name: http
              protocol: TCP
        readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3111
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
        